apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_HOST: mysql
  DATABASE_PORT: "3306"
  DATABASE_NAME: lanchonete
  MP_URL: "https://api.mercadopago.com/"
  MP_ACCESS_TOKEN: "APP_USR-5776470819795291-052622-9d0e16330f82db26018b57af9f373d82-2461182756"
  MP_USER_ID: "2461182756"
  MP_EXTERNAL_POS_ID: "113730756"